version: '3.8'

services:

  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: investments
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  node-app:
    build: .
    depends_on:
      - postgres-db
    ports:
      - 3000:3000



  react-app:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - node-app
